//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace utlPortal.utlApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="utlAPISoap", Namespace="http://tempuri.org/")]
    public partial class utlAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestFloatsToQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback FloatCreditsToQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFloatRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public utlAPI() {
            this.Url = global::utlPortal.Properties.Settings.Default.utlPortal_utlApi_utlAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestFloatsToQueueCompletedEventHandler RequestFloatsToQueueCompleted;
        
        /// <remarks/>
        public event FloatCreditsToQueueCompletedEventHandler FloatCreditsToQueueCompleted;
        
        /// <remarks/>
        public event AddAgentCompletedEventHandler AddAgentCompleted;
        
        /// <remarks/>
        public event AddAdminCompletedEventHandler AddAdminCompleted;
        
        /// <remarks/>
        public event GetAdminCompletedEventHandler GetAdminCompleted;
        
        /// <remarks/>
        public event GetAgentDetailsCompletedEventHandler GetAgentDetailsCompleted;
        
        /// <remarks/>
        public event GetFloatRequestsCompletedEventHandler GetFloatRequestsCompleted;
        
        /// <remarks/>
        public event GetCreditsCompletedEventHandler GetCreditsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestFloatsToQueue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestFloatsToQueue(decimal FloatAmount, int AgentId) {
            object[] results = this.Invoke("RequestFloatsToQueue", new object[] {
                        FloatAmount,
                        AgentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestFloatsToQueueAsync(decimal FloatAmount, int AgentId) {
            this.RequestFloatsToQueueAsync(FloatAmount, AgentId, null);
        }
        
        /// <remarks/>
        public void RequestFloatsToQueueAsync(decimal FloatAmount, int AgentId, object userState) {
            if ((this.RequestFloatsToQueueOperationCompleted == null)) {
                this.RequestFloatsToQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestFloatsToQueueOperationCompleted);
            }
            this.InvokeAsync("RequestFloatsToQueue", new object[] {
                        FloatAmount,
                        AgentId}, this.RequestFloatsToQueueOperationCompleted, userState);
        }
        
        private void OnRequestFloatsToQueueOperationCompleted(object arg) {
            if ((this.RequestFloatsToQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestFloatsToQueueCompleted(this, new RequestFloatsToQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FloatCreditsToQueue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FloatCreditsToQueue(decimal FloatAmount, int AgentId) {
            object[] results = this.Invoke("FloatCreditsToQueue", new object[] {
                        FloatAmount,
                        AgentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FloatCreditsToQueueAsync(decimal FloatAmount, int AgentId) {
            this.FloatCreditsToQueueAsync(FloatAmount, AgentId, null);
        }
        
        /// <remarks/>
        public void FloatCreditsToQueueAsync(decimal FloatAmount, int AgentId, object userState) {
            if ((this.FloatCreditsToQueueOperationCompleted == null)) {
                this.FloatCreditsToQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFloatCreditsToQueueOperationCompleted);
            }
            this.InvokeAsync("FloatCreditsToQueue", new object[] {
                        FloatAmount,
                        AgentId}, this.FloatCreditsToQueueOperationCompleted, userState);
        }
        
        private void OnFloatCreditsToQueueOperationCompleted(object arg) {
            if ((this.FloatCreditsToQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FloatCreditsToQueueCompleted(this, new FloatCreditsToQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddAgent(string Name, string PhoneNumber, decimal FloatAmount) {
            object[] results = this.Invoke("AddAgent", new object[] {
                        Name,
                        PhoneNumber,
                        FloatAmount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddAgentAsync(string Name, string PhoneNumber, decimal FloatAmount) {
            this.AddAgentAsync(Name, PhoneNumber, FloatAmount, null);
        }
        
        /// <remarks/>
        public void AddAgentAsync(string Name, string PhoneNumber, decimal FloatAmount, object userState) {
            if ((this.AddAgentOperationCompleted == null)) {
                this.AddAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAgentOperationCompleted);
            }
            this.InvokeAsync("AddAgent", new object[] {
                        Name,
                        PhoneNumber,
                        FloatAmount}, this.AddAgentOperationCompleted, userState);
        }
        
        private void OnAddAgentOperationCompleted(object arg) {
            if ((this.AddAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAgentCompleted(this, new AddAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddAdmin(string Name, string Password) {
            object[] results = this.Invoke("AddAdmin", new object[] {
                        Name,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddAdminAsync(string Name, string Password) {
            this.AddAdminAsync(Name, Password, null);
        }
        
        /// <remarks/>
        public void AddAdminAsync(string Name, string Password, object userState) {
            if ((this.AddAdminOperationCompleted == null)) {
                this.AddAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAdminOperationCompleted);
            }
            this.InvokeAsync("AddAdmin", new object[] {
                        Name,
                        Password}, this.AddAdminOperationCompleted, userState);
        }
        
        private void OnAddAdminOperationCompleted(object arg) {
            if ((this.AddAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAdminCompleted(this, new AddAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAdmin(string name, string password) {
            object[] results = this.Invoke("GetAdmin", new object[] {
                        name,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdminAsync(string name, string password) {
            this.GetAdminAsync(name, password, null);
        }
        
        /// <remarks/>
        public void GetAdminAsync(string name, string password, object userState) {
            if ((this.GetAdminOperationCompleted == null)) {
                this.GetAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdminOperationCompleted);
            }
            this.InvokeAsync("GetAdmin", new object[] {
                        name,
                        password}, this.GetAdminOperationCompleted, userState);
        }
        
        private void OnGetAdminOperationCompleted(object arg) {
            if ((this.GetAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdminCompleted(this, new GetAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Agents GetAgentDetails(int id) {
            object[] results = this.Invoke("GetAgentDetails", new object[] {
                        id});
            return ((Agents)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentDetailsAsync(int id) {
            this.GetAgentDetailsAsync(id, null);
        }
        
        /// <remarks/>
        public void GetAgentDetailsAsync(int id, object userState) {
            if ((this.GetAgentDetailsOperationCompleted == null)) {
                this.GetAgentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentDetailsOperationCompleted);
            }
            this.InvokeAsync("GetAgentDetails", new object[] {
                        id}, this.GetAgentDetailsOperationCompleted, userState);
        }
        
        private void OnGetAgentDetailsOperationCompleted(object arg) {
            if ((this.GetAgentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentDetailsCompleted(this, new GetAgentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFloatRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetFloatRequests() {
            object[] results = this.Invoke("GetFloatRequests", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetFloatRequestsAsync() {
            this.GetFloatRequestsAsync(null);
        }
        
        /// <remarks/>
        public void GetFloatRequestsAsync(object userState) {
            if ((this.GetFloatRequestsOperationCompleted == null)) {
                this.GetFloatRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFloatRequestsOperationCompleted);
            }
            this.InvokeAsync("GetFloatRequests", new object[0], this.GetFloatRequestsOperationCompleted, userState);
        }
        
        private void OnGetFloatRequestsOperationCompleted(object arg) {
            if ((this.GetFloatRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFloatRequestsCompleted(this, new GetFloatRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCredits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCredits() {
            object[] results = this.Invoke("GetCredits", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditsAsync() {
            this.GetCreditsAsync(null);
        }
        
        /// <remarks/>
        public void GetCreditsAsync(object userState) {
            if ((this.GetCreditsOperationCompleted == null)) {
                this.GetCreditsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditsOperationCompleted);
            }
            this.InvokeAsync("GetCredits", new object[0], this.GetCreditsOperationCompleted, userState);
        }
        
        private void OnGetCreditsOperationCompleted(object arg) {
            if ((this.GetCreditsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditsCompleted(this, new GetCreditsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agents {
        
        private int agentIdField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private decimal floatAmountField;
        
        /// <remarks/>
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal FloatAmount {
            get {
                return this.floatAmountField;
            }
            set {
                this.floatAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequestFloatsToQueueCompletedEventHandler(object sender, RequestFloatsToQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestFloatsToQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestFloatsToQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FloatCreditsToQueueCompletedEventHandler(object sender, FloatCreditsToQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FloatCreditsToQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FloatCreditsToQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddAgentCompletedEventHandler(object sender, AddAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddAdminCompletedEventHandler(object sender, AddAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAdminCompletedEventHandler(object sender, GetAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAgentDetailsCompletedEventHandler(object sender, GetAgentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agents Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agents)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFloatRequestsCompletedEventHandler(object sender, GetFloatRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFloatRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFloatRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetCreditsCompletedEventHandler(object sender, GetCreditsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591